### PR TITLE
SONARJNKNS-216 Make the SonarQube badge a link

### PR DESCRIPTION
**Pull request by dbmeneses**

### CODE REVIEW

**Comment by henryju** [comment]
LGTM

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR Add a 'package-info.java' file to document the 'sonar' package (org.jenkins-ci.plugins:sonar:target/generated-sources/localizer/hudson/plugins/sonar) [rule](https://dory.internal.sonarsource.com/coding_rules#rule_key=squid%3AS1228)

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR Add a 'package-info.java' file to document the 'sonar' package (org.jenkins-ci.plugins:sonar:target/generated-sources/localizer/hudson/plugins/sonar) [rule](https://dory.internal.sonarsource.com/coding_rules#rule_key=squid%3AS1228)

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR Add a 'package-info.java' file to document the 'sonar' package (org.jenkins-ci.plugins:sonar:target/generated-sources/localizer/hudson/plugins/sonar) [rule](https://dory.internal.sonarsource.com/coding_rules#rule_key=squid%3AS1228)

**Pull request closed without merging**
