### PR TITLE
[JENKINS-33417] - Fixed circular dependency warning on Startup

### PR DESCRIPTION
**Pull request by Dohbedoh**
@reviewbybees

### CODE REVIEW

**Comment by dbmeneses** [comment]
How did you came to the conclusion that there is a circular dependency?

**Comment by Dohbedoh** [comment]
This is a warning produced by Jenkins when loading configuration on startup: `Tried proxying hudson.plugins.sonar.SonarGlobalConfiguration to support a circular dependency, but it is not an interface`. (see [JENKINS-33417|https://issues.jenkins-ci.org/browse/JENKINS-33417])

**Comment by dbmeneses** [comment]
Ok thanks

**Comment by chitraj8** [comment]
I see there is latest version sonar-plugin:2.4 will that be having this issue fixed?

**Comment by Dohbedoh** [comment]
@chitraj8 sonar-plugin:2.4 has been released before this fix was merged and therefore does not contain this fix.

**Comment by dbmeneses** [comment]
@chitraj8 v2.4.1 will be released in the next few days and will include the fix.

**Pull request merged**
